### ISSUE TITLE
Cannot download data and models

### ISSUE THREAD

**Issue by JJavier98** [IdiosyncraticDragon/SiPO#20]
Hello, I am unable to download the data resources and models.
I need to be registered on the database website, but I cannot complete the process from Spain.
Could you upload the files to another platform that is more easily accessible from other countries, please?

**Comment by IdiosyncraticDragon** [comment]
I have uploaded the data and models to Google Drive and updated the readme with the links. 
Here are the share links of google drive :
Data: https://drive.google.com/drive/folders/10mkzaOJggAlbOwZqaZ6R07VnIbEEPlWy?usp=share_link
Original model: https://drive.google.com/drive/folders/1imkA2Fq5OyMhOxlcbgpymScbxCGBL1hF?usp=share_link
Pruned model: https://drive.google.com/drive/folders/1RKpRbu_W7kCNK-qy1WeuUsEacLfXqRgx?usp=share_link
